/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExElevador;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner leitor = new Scanner(System.in);

        Elevador elevador = new Elevador(12, 20);
        int x;
        do {
            System.out.println("Voce deseja inicializar o elevador, adicionar pessoa ao elevador, remover pessoa do elevador, subir andar do elevador ou descer andar do elevador?\n1 - Inicializar\n2 - Adicionar\n3 - Remover\n4 - Subir\n 5 - Descer\n 6 - Sair");
            x = leitor.nextInt();
            switch (x) {
                case 1:
                    elevador.Inicializa();
                    break;
                case 2:
                    System.out.println("Indique quantas pessoas entrarao no elevador: ");
                    elevador.Entra(leitor.nextInt());
                    break;
                case 3:
                    System.out.println("Indique quantas pessoas sairao no elevador: ");
                    elevador.Sai(leitor.nextInt());
                    break;
                case 4:
                    System.out.println("Indique quantos andares o elevador devera subir: ");
                    elevador.Sobe(leitor.nextInt());
                    break;
                case 5:
                    System.out.println("Indique quantos andares o elevador devera descer: ");
                    elevador.Desce(leitor.nextInt());
                    break;
                case 6:
                    break;
            }
        } while (x != 6);
    }

}
